"""Seed authoritative opportunity sources and sample verified opportunities."""
from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone
from sqlalchemy.orm import Session

from app.models.enums import (
    OpportunityAuthorityLevel,
    OpportunityDeadlineStatus,
    OpportunitySourceType,
    OpportunityType,
)
from app.models.opportunity import Opportunity, OpportunityLink, OpportunitySource
from app.modules.opportunities.ingestion.deduplicator import compute_content_hash


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def seed(session: Session) -> dict:
    # 1. Seed Sources
    sources_data = [
        # Central Government & National Portals
        {
            "name": "National Career Service (NCS)",
            "domain": "ncs.gov.in",
            "base_url": "https://www.ncs.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Recruitment & Job Fairs",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "30_minutes",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["JOB", "JOB_FAIR", "INTERNSHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "myScheme Portal",
            "domain": "myscheme.gov.in",
            "base_url": "https://www.myscheme.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Government Schemes & Welfare",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "30_minutes",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["GOVERNMENT_SCHEME"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "National Scholarship Portal (NSP)",
            "domain": "scholarships.gov.in",
            "base_url": "https://scholarships.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "National Scholarships",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "1_hour",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["SCHOLARSHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Union Public Service Commission (UPSC)",
            "domain": "upsc.gov.in",
            "base_url": "https://upsc.gov.in",
            "source_type": OpportunitySourceType.PUBLIC_INSTITUTION,
            "source_category": "Civil Services Recruitment",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "1_hour",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "India Government Portal",
            "domain": "india.gov.in",
            "base_url": "https://www.india.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Government Services & Schemes",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "3_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["GOVERNMENT_SCHEME", "JOB"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "National Apprenticeship Promotion Scheme (NAPS)",
            "domain": "apprenticeshipindia.gov.in",
            "base_url": "https://www.apprenticeshipindia.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Apprenticeships & Skill Training",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "1_hour",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["APPRENTICESHIP", "TRAINING"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "National Apprenticeship Training Scheme (NATS)",
            "domain": "nats.education.gov.in",
            "base_url": "https://nats.education.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Technical Apprenticeships",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "3_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["APPRENTICESHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "PM Internship Scheme Portal",
            "domain": "pminternship.mca.gov.in",
            "base_url": "https://pminternship.mca.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Corporate Internships",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "30_minutes",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["INTERNSHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Prime Minister Research Fellowship (PMRF)",
            "domain": "pmrf.in",
            "base_url": "https://www.pmrf.in",
            "source_type": OpportunitySourceType.PUBLIC_INSTITUTION,
            "source_category": "Doctoral Research Fellowships",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "3_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["FELLOWSHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Skill India Digital Portal",
            "domain": "skillindiadigital.gov.in",
            "base_url": "https://www.skillindiadigital.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Skill Certification & Training",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "3_hours",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["SKILL_PROGRAM", "TRAINING"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Skill India Portal",
            "domain": "skillindia.gov.in",
            "base_url": "https://www.skillindia.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Skill Development",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "3_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["SKILL_PROGRAM", "TRAINING"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Staff Selection Commission (SSC)",
            "domain": "ssc.gov.in",
            "base_url": "https://ssc.gov.in",
            "source_type": OpportunitySourceType.PUBLIC_INSTITUTION,
            "source_category": "Staff Recruitment",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "1_hour",
            "priority": "P0",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "CSIR Human Resource Development Group (CSIR-HRDG)",
            "domain": "csirhrdg.res.in",
            "base_url": "https://csirhrdg.res.in",
            "source_type": OpportunitySourceType.PUBLIC_INSTITUTION,
            "source_category": "Research Fellowships & NET",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "3_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["FELLOWSHIP", "GRANT"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Biotechnology Industry Research Assistance Council (BIRAC)",
            "domain": "birac.nic.in",
            "base_url": "https://birac.nic.in",
            "source_type": OpportunitySourceType.PUBLIC_INSTITUTION,
            "source_category": "Biotech Grants & Innovation",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["GRANT"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Smart India Hackathon (SIH Portal)",
            "domain": "sih.gov.in",
            "base_url": "https://sih.gov.in",
            "source_type": OpportunitySourceType.CENTRAL_GOVERNMENT,
            "source_category": "Innovation Hackathons & Competitions",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["COMPETITION"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "National Testing Agency (NTA Admission Portal)",
            "domain": "nta.ac.in",
            "base_url": "https://nta.ac.in",
            "source_type": OpportunitySourceType.PUBLIC_INSTITUTION,
            "source_category": "National Admissions & Entrance Exams",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["ADMISSION"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "National Institute of Electronics & Information Technology (NIELIT)",
            "domain": "nielit.gov.in",
            "base_url": "https://nielit.gov.in",
            "source_type": OpportunitySourceType.PUBLIC_INSTITUTION,
            "source_category": "IT & Electronics Training",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["TRAINING", "SKILL_PROGRAM"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },

        # State Government Public Service Commissions & Recruitment Boards
        {
            "name": "Maharashtra Public Service Commission (MPSC)",
            "domain": "mpsc.gov.in",
            "base_url": "https://mpsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Maharashtra",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Karnataka Public Service Commission (KPSC)",
            "domain": "kpsc.kar.nic.in",
            "base_url": "https://kpsc.kar.nic.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Karnataka",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Tamil Nadu Public Service Commission (TNPSC)",
            "domain": "tnpsc.gov.in",
            "base_url": "https://www.tnpsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Tamil Nadu",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Uttar Pradesh Public Service Commission (UPPSC)",
            "domain": "uppsc.up.nic.in",
            "base_url": "https://uppsc.up.nic.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Uttar Pradesh",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "West Bengal Public Service Commission (WBPSC)",
            "domain": "psc.wb.gov.in",
            "base_url": "https://psc.wb.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "West Bengal",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Rajasthan Public Service Commission (RPSC)",
            "domain": "rpsc.rajasthan.gov.in",
            "base_url": "https://rpsc.rajasthan.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Rajasthan",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Bihar Public Service Commission (BPSC)",
            "domain": "bpsc.bih.nic.in",
            "base_url": "https://bpsc.bih.nic.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Bihar",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Gujarat Public Service Commission (GPSC)",
            "domain": "gpsc.gujarat.gov.in",
            "base_url": "https://gpsc.gujarat.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Gujarat",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Kerala Public Service Commission (Kerala PSC)",
            "domain": "keralapsc.gov.in",
            "base_url": "https://www.keralapsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Kerala",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Madhya Pradesh Public Service Commission (MPPSC)",
            "domain": "mppsc.mp.gov.in",
            "base_url": "https://mppsc.mp.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Madhya Pradesh",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Telangana State Public Service Commission (TSPSC)",
            "domain": "tspsc.gov.in",
            "base_url": "https://www.tspsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Telangana",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Andhra Pradesh Public Service Commission (APPSC)",
            "domain": "psc.ap.gov.in",
            "base_url": "https://psc.ap.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Andhra Pradesh",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Odisha Public Service Commission (OPSC)",
            "domain": "opsc.gov.in",
            "base_url": "https://www.opsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Odisha",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Punjab Public Service Commission (PPSC)",
            "domain": "ppsc.gov.in",
            "base_url": "https://ppsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Punjab",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Haryana Public Service Commission (HPSC)",
            "domain": "hpsc.gov.in",
            "base_url": "http://hpsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Haryana",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Assam Public Service Commission (APSC)",
            "domain": "apsc.nic.in",
            "base_url": "http://apsc.nic.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Assam",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Jharkhand Public Service Commission (JPSC)",
            "domain": "jpsc.gov.in",
            "base_url": "https://www.jpsc.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "State Recruitment",
            "country": "IN",
            "state": "Jharkhand",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },
        {
            "name": "Delhi Subordinate Services Selection Board (DSSSB)",
            "domain": "dsssb.delhi.gov.in",
            "base_url": "https://dsssb.delhi.gov.in",
            "source_type": OpportunitySourceType.STATE_GOVERNMENT,
            "source_category": "UT Recruitment",
            "country": "IN",
            "state": "Delhi",
            "authority_level": OpportunityAuthorityLevel.OFFICIAL,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB"],
            "geographic_scope": "STATE",
            "enabled": True,
        },

        # Direct Corporate Careers Portals
        {
            "name": "Tata Consultancy Services Careers",
            "domain": "tcs.com",
            "base_url": "https://www.tcs.com/careers",
            "source_type": OpportunitySourceType.PRIVATE_COMPANY,
            "source_category": "Private Industry Careers & Internships",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.KNOWN_PRIVATE,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB", "INTERNSHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Infosys Careers Portal",
            "domain": "infosys.com",
            "base_url": "https://www.infosys.com/careers",
            "source_type": OpportunitySourceType.PRIVATE_COMPANY,
            "source_category": "Private Industry Careers",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.KNOWN_PRIVATE,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB", "INTERNSHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
        {
            "name": "Wipro Careers Portal",
            "domain": "wipro.com",
            "base_url": "https://www.wipro.com/careers",
            "source_type": OpportunitySourceType.PRIVATE_COMPANY,
            "source_category": "Private Industry Careers",
            "country": "IN",
            "authority_level": OpportunityAuthorityLevel.KNOWN_PRIVATE,
            "crawl_frequency": "6_hours",
            "priority": "P1",
            "connector_type": "HTML",
            "opportunity_types": ["JOB", "INTERNSHIP"],
            "geographic_scope": "NATIONAL",
            "enabled": True,
        },
    ]

    created_sources = []
    for s_data in sources_data:
        existing = session.query(OpportunitySource).filter(OpportunitySource.domain == s_data["domain"]).first()
        if not existing:
            src = OpportunitySource(**s_data)
            src.last_crawled_at = _utc_now() - timedelta(minutes=15)
            src.last_successful_crawl_at = _utc_now() - timedelta(minutes=15)
            session.add(src)
            session.flush()
            created_sources.append(src)
        else:
            created_sources.append(existing)

    session.commit()

    # 2. Seed Sample Verified Opportunities
    ncs_src = next((s for s in created_sources if s.domain == "ncs.gov.in"), created_sources[0])
    nsp_src = next((s for s in created_sources if s.domain == "scholarships.gov.in"), created_sources[0])
    tcs_src = next((s for s in created_sources if s.domain == "tcs.com"), created_sources[0])
    upsc_src = next((s for s in created_sources if s.domain == "upsc.gov.in"), created_sources[0])

    now = _utc_now()

    sample_opps = [
        {
            "type": OpportunityType.JOB,
            "title": "Assistant Engineer (Civil & Electrical) Recruitment 2026",
            "organization": "Central Public Works Department (CPWD)",
            "organization_type": "Government Ministry",
            "description": "Recruitment notification for Assistant Engineers across India. Candidates will be responsible for planning, executing, and supervising public infrastructure projects.",
            "summary": "Central Government engineering vacancies for B.Tech/BE graduates.",
            "location": "New Delhi, India",
            "locations": ["New Delhi", "Mumbai", "Kolkata", "Chennai", "Bengaluru"],
            "remote": False,
            "employment_type": "Full-time",
            "category": "Engineering",
            "sector": "Public Sector",
            "skills": ["Civil Engineering", "Project Management", "AutoCAD", "Structural Analysis"],
            "education_requirements": ["Graduate", "B.Tech", "B.E."],
            "experience_requirements": {"min_years": 0, "max_years": 3},
            "age_requirements": {"min": 21, "max": 30},
            "income_requirements": {},
            "citizenship_requirements": ["Indian National"],
            "gender_requirements": ["Any"],
            "state_requirements": [],
            "category_requirements": ["General", "OBC", "SC", "ST", "EWS"],
            "eligibility": ["Must hold a recognized Bachelor's Degree in Engineering.", "Age between 21 and 30 years as of closing date."],
            "benefits": ["Level 10 Pay Matrix (Rs. 56,100 - 1,77,500)", "Dearness Allowance", "HRA & Medical Benefits"],
            "salary_min": 56100.0,
            "salary_max": 177500.0,
            "stipend": None,
            "fee": "Rs. 100 (Exempted for Women/SC/ST/PwD)",
            "application_open_date": now - timedelta(days=10),
            "application_deadline": now + timedelta(days=4),  # Closing soon
            "published_at": now - timedelta(days=10),
            "status": OpportunityDeadlineStatus.CLOSING_SOON,
            "source_url": "https://www.ncs.gov.in/job-seeker/Pages/Search.aspx?id=CPWD-AE-2026",
            "application_url": "https://www.ncs.gov.in/apply/CPWD-AE-2026",
            "source_domain": "ncs.gov.in",
            "source_name": ncs_src.name,
            "source_type": ncs_src.source_type.value,
            "source_identifier": "CPWD-AE-2026",
            "source_id": ncs_src.id,
            "quality_score": 0.95,
            "extraction_confidence": 0.98,
            "is_canonical": True,
            "last_seen_at": now,
            "last_verified_at": now,
        },
        {
            "type": OpportunityType.SCHOLARSHIP,
            "title": "Central Sector Scheme of Scholarships for College and University Students 2026",
            "organization": "Department of Higher Education, Ministry of Education",
            "organization_type": "Central Ministry",
            "description": "Financial assistance to meritorious students from low-income families to meet a part of their day-to-day expenses while pursuing higher studies.",
            "summary": "Rs. 12,000 to Rs. 20,000 per annum scholarship for graduate & post-graduate students.",
            "location": "All India",
            "locations": ["All India"],
            "remote": True,
            "employment_type": "Scholarship",
            "category": "Education",
            "sector": "Government Scheme",
            "skills": [],
            "education_requirements": ["Higher Secondary (12th Passed)", "Undergraduate Student"],
            "experience_requirements": {},
            "age_requirements": {"min": 17, "max": 25},
            "income_requirements": {"max_annual_income": 450000.0},
            "citizenship_requirements": ["Indian National"],
            "gender_requirements": ["Any"],
            "state_requirements": [],
            "category_requirements": ["General", "OBC", "SC", "ST"],
            "eligibility": [
                "Top 20th percentile in Class 12th board exams.",
                "Family annual income below Rs. 4.5 Lakh.",
                "Pursuing regular degree course in recognized university/college.",
            ],
            "benefits": ["Rs. 12,000/year at graduation level for first 3 years", "Rs. 20,000/year at post-graduation level"],
            "salary_min": None,
            "salary_max": None,
            "stipend": "Rs. 12,000 - 20,000 / year",
            "fee": "Nil",
            "application_open_date": now - timedelta(days=20),
            "application_deadline": now + timedelta(days=15),
            "published_at": now - timedelta(days=20),
            "status": OpportunityDeadlineStatus.OPEN,
            "source_url": "https://scholarships.gov.in/scheme-detail/CS-2026",
            "application_url": "https://scholarships.gov.in/fresh-application-2026",
            "source_domain": "scholarships.gov.in",
            "source_name": nsp_src.name,
            "source_type": nsp_src.source_type.value,
            "source_identifier": "NSP-CS-2026",
            "source_id": nsp_src.id,
            "quality_score": 0.98,
            "extraction_confidence": 0.99,
            "is_canonical": True,
            "last_seen_at": now,
            "last_verified_at": now,
        },
        {
            "type": OpportunityType.INTERNSHIP,
            "title": "TCS National Qualifier Test (NQT) & Internship Drive 2026",
            "organization": "Tata Consultancy Services",
            "organization_type": "Private Enterprise",
            "description": "Exclusive internship opportunity for pre-final and final year engineering & science students with hands-on software project training and stipend.",
            "summary": "Software engineering internships in Bangalore, Pune, and Hyderabad with flexible hybrid mode.",
            "location": "Bengaluru, Karnataka",
            "locations": ["Bengaluru", "Pune", "Hyderabad", "Noida"],
            "remote": True,
            "employment_type": "Internship",
            "category": "Technology",
            "sector": "Information Technology",
            "skills": ["Python", "Java", "Data Structures", "Web Development", "SQL"],
            "education_requirements": ["B.Tech", "B.E.", "M.Tech", "MCA", "B.Sc CS"],
            "experience_requirements": {"max_years": 1},
            "age_requirements": {"min": 18, "max": 26},
            "income_requirements": {},
            "citizenship_requirements": ["Indian National"],
            "gender_requirements": ["Any"],
            "state_requirements": [],
            "category_requirements": [],
            "eligibility": [
                "Final year or recent graduate with minimum 60% in graduation.",
                "Basic proficiency in programming (Python/Java/C++).",
            ],
            "benefits": ["Monthly Stipend Rs. 25,000", "Pre-Placement Offer (PPO) opportunities", "Industry Mentorship"],
            "salary_min": None,
            "salary_max": None,
            "stipend": "Rs. 25,000 / month",
            "fee": "Nil",
            "application_open_date": now - timedelta(days=5),
            "application_deadline": now + timedelta(days=20),
            "published_at": now - timedelta(days=5),
            "status": OpportunityDeadlineStatus.OPEN,
            "source_url": "https://www.tcs.com/careers/nqt-internship-2026",
            "application_url": "https://www.tcs.com/careers/apply-internship-2026",
            "source_domain": "tcs.com",
            "source_name": tcs_src.name,
            "source_type": tcs_src.source_type.value,
            "source_identifier": "TCS-NQT-2026",
            "source_id": tcs_src.id,
            "quality_score": 0.90,
            "extraction_confidence": 0.95,
            "is_canonical": True,
            "last_seen_at": now,
            "last_verified_at": now,
        },
        {
            "type": OpportunityType.JOB,
            "title": "Civil Services Examination (CSE) 2026 Notification",
            "organization": "Union Public Service Commission (UPSC)",
            "organization_type": "Public Commission",
            "description": "Prestigious competitive examination for recruitment to administrative, diplomatic, police, and revenue civil services of India.",
            "summary": "UPSC Civil Services Prelims 2026 official notice.",
            "location": "All India",
            "locations": ["All India"],
            "remote": False,
            "employment_type": "Full-time",
            "category": "Administration",
            "sector": "Civil Services",
            "skills": ["Public Administration", "General Studies", "Analytical Reasoning"],
            "education_requirements": ["Graduate"],
            "experience_requirements": {},
            "age_requirements": {"min": 21, "max": 32},
            "income_requirements": {},
            "citizenship_requirements": ["Citizen of India"],
            "gender_requirements": ["Any"],
            "state_requirements": [],
            "category_requirements": [],
            "eligibility": ["Degree of a recognized University.", "Age 21 to 32 years with relaxation for reserved categories."],
            "benefits": ["IAS/IFS/IPS Cadre Pay Scale", "Government Housing & Security"],
            "salary_min": 56100.0,
            "salary_max": 250000.0,
            "stipend": None,
            "fee": "Rs. 100",
            "application_open_date": now - timedelta(days=12),
            "application_deadline": now + timedelta(days=2),  # Closing soon
            "published_at": now - timedelta(days=12),
            "status": OpportunityDeadlineStatus.CLOSING_SOON,
            "source_url": "https://upsc.gov.in/examinations/civil-services-2026",
            "application_url": "https://upsconline.nic.in/apply-cse-2026",
            "source_domain": "upsc.gov.in",
            "source_name": upsc_src.name,
            "source_type": upsc_src.source_type.value,
            "source_identifier": "UPSC-CSE-2026",
            "source_id": upsc_src.id,
            "quality_score": 0.99,
            "extraction_confidence": 1.0,
            "is_canonical": True,
            "last_seen_at": now,
            "last_verified_at": now,
        },
        {
            "type": OpportunityType.JOB_FAIR,
            "title": "National Mega Job Fair & Apprenticeship Mela 2026",
            "organization": "National Career Service (NCS)",
            "organization_type": "Government Portal",
            "description": "National Level Mega Job Fair & Apprenticeship Drive bringing together 500+ top employers for direct spot interviews, placement offers, and skill counseling.",
            "summary": "Mega Job Fair across major cities in India providing instant employment offers for IT, Engineering, and Non-Tech graduates.",
            "location": "All India",
            "locations": ["New Delhi", "Mumbai", "Bengaluru", "Kolkata", "Chennai", "Hyderabad", "Pune"],
            "remote": False,
            "employment_type": "Full-time",
            "category": "Employment Fair",
            "sector": "Multi-Sector",
            "skills": ["Communication", "Technical Skills", "Aptitude", "Interview Skills"],
            "education_requirements": ["10th", "12th", "ITI", "Diploma", "Graduate", "B.Tech"],
            "experience_requirements": {"min_years": 0, "max_years": 5},
            "age_requirements": {"min": 18, "max": 35},
            "income_requirements": {},
            "citizenship_requirements": ["Indian National"],
            "gender_requirements": ["Any"],
            "state_requirements": [],
            "category_requirements": [],
            "eligibility": ["Open to all job seekers registered on NCS Portal.", "Carry updated resumes and ID proofs."],
            "benefits": ["On-the-spot interviews", "Direct hiring by top MNCs and PSUs", "Free Registration"],
            "salary_min": 180000.0,
            "salary_max": 800000.0,
            "stipend": None,
            "fee": "Free Registration",
            "application_open_date": now - timedelta(days=5),
            "application_deadline": now + timedelta(days=10),
            "published_at": now - timedelta(days=5),
            "status": OpportunityDeadlineStatus.OPEN,
            "source_url": "https://www.ncs.gov.in/job-fairs/mega-job-fair-2026",
            "application_url": "https://www.ncs.gov.in/job-seeker/Pages/JobFairDetails.aspx",
            "source_domain": "ncs.gov.in",
            "source_name": ncs_src.name,
            "source_type": ncs_src.source_type.value,
            "source_identifier": "NCS-JOBFAIR-2026",
            "source_id": ncs_src.id,
            "quality_score": 0.98,
            "extraction_confidence": 1.0,
            "is_canonical": True,
            "last_seen_at": now,
            "last_verified_at": now,
        },
    ]

    seeded_count = 0
    for opp_data in sample_opps:
        chash = compute_content_hash(opp_data["organization"], opp_data["title"], str(opp_data["application_deadline"]))
        opp_data["content_hash"] = chash

        existing_opp = session.query(Opportunity).filter(Opportunity.content_hash == chash).first()
        if not existing_opp:
            opp = Opportunity(**opp_data)
            session.add(opp)
            session.flush()

            # Add primary official link
            link = OpportunityLink(
                opportunity_id=opp.id,
                url=opp.application_url or opp.source_url,
                domain=opp.source_domain,
                is_official=True,
                is_valid=True,
                verified_at=now,
                http_status=200,
            )
            session.add(link)
            seeded_count += 1

    session.commit()
    return {"sources_seeded": len(created_sources), "opportunities_seeded": seeded_count}


if __name__ == "__main__":
    from app.db.session import get_sessionmaker

    session = get_sessionmaker()()
    try:
        res = seed(session)
        print(f"Seeded opportunity discovery engine: {res}")
    finally:
        session.close()
